### Numpy

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically)

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

In [3]:
import numpy as np

In [4]:
a = np.array ([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# 2D array ::: 2*3 -> Two: three columns 1D array
b = np.array([
             [2,3,4],
             [4,6,7]
            ])
print(b) # A 2D array is bunch of 1D array

[[2 3 4]
 [4 6 7]]


In [6]:
# 3D array ::: A bunch of 2D array 2*(2*3) -> Two 2*3 2D array => Two (Two: three columns 1D array)
c = ([
    [[2,3,4],[5,7,9]],
    [[9,7,0],[2,4,6]]
])
print(c)

[[[2, 3, 4], [5, 7, 9]], [[9, 7, 0], [2, 4, 6]]]


In [11]:
# dtype
np.array([1, 2, -4, 0],dtype=complex)

array([ 1.+0.j,  2.+0.j, -4.+0.j,  0.+0.j])

In [12]:
# np.arange ::: similar to range in python
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
# reshape
np.arange(1,11).reshape(5,2) # Five rows and two columns

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
np.arange(1,17).reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [21]:
# np.ones and np.zeros
np.ones((3,4)) # takes tuple as parameter

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4)) # takes tuple as parameter

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# np.random
np.random.random((3,4)) # zero se one ke beech random no.s

array([[0.99345838, 0.05835388, 0.94362746, 0.44219646],
       [0.84223715, 0.14261589, 0.29327489, 0.94639307],
       [0.2780636 , 0.33962607, 0.45050107, 0.96011994]])

In [27]:
# np.linspace ::: linear space -> equal distance par points generate kar dega
np.linspace(-10,10,10) # <lower_range, upper_range, no. of numbers>

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [28]:
# np.identity
np.identity(3) # 3*3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes 

In [32]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [36]:
# ndim ::: no. of dimensions
a3.ndim

3

In [37]:
a1.ndim

1

In [43]:
# shape ::: haar dimension mein kitne elements hain
a1.shape

(10,)

In [39]:
a2.shape

(3, 4)

In [40]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [41]:
a3.shape

(2, 2, 2)

In [42]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [46]:
# size ::: how many total no. of items
a3.size

8

In [47]:
a2.size

12

In [51]:
# itemsize ::: haar item memory mein kitna size le raha hai

a1.itemsize

4

In [52]:
a2.itemsize

8

In [53]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [55]:
# astype
a3.dtype

dtype('int32')

In [58]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

In [60]:
a3.dtype

dtype('int32')

### Array Operation 

In [61]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### Scalar Operation

In [70]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
# Arithmetic 
a1 *2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [72]:
# Relational
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [73]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

##### Vector Operation 

In [74]:
# Arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [102]:
a1*a2 # Element to element multiply

array([[ 936.,  468.,  140.,   45.],
       [  64., 1326., 1764., 1615.],
       [1120., 2058., 1474., 1357.]])

### Array Functions 

In [78]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1

array([[78., 36., 10.,  3.],
       [ 4., 78., 98., 85.],
       [56., 98., 67., 59.]])

In [79]:
np.min(a1)

3.0

In [80]:
np.max(a1)

98.0

In [81]:
np.sum(a1)

672.0

In [91]:
np.prod(a1)

4.749620065266586e+18

In [87]:
np.min(a1,axis=1) # 0 = Column, 1 = Row

array([ 3.,  4., 56.])

In [88]:
a1

array([[78., 36., 10.,  3.],
       [ 4., 78., 98., 85.],
       [56., 98., 67., 59.]])

In [89]:
np.max(a1, axis=0)

array([78., 98., 98., 85.])

In [90]:
np.prod(a1,axis=0)

array([ 17472., 275184.,  65660.,  15045.])

##### Mean/Median/Std/Var

In [93]:
np.mean(a1)

56.0

In [94]:
np.mean(a1,axis=1)

array([31.75, 66.25, 70.  ])

In [96]:
np.median(a1)

63.0

In [97]:
np.std(a1)

33.53605025441527

In [98]:
np.var(a1)

1124.6666666666667

##### Trigonometric Functions 

In [100]:
np.sin(a1)

array([[ 0.51397846, -0.99177885, -0.54402111,  0.14112001],
       [-0.7568025 ,  0.51397846, -0.57338187, -0.17607562],
       [-0.521551  , -0.57338187, -0.85551998,  0.63673801]])

In [101]:
np.tan(a1)

array([[-0.59918   ,  7.75047091,  0.64836083, -0.14254654],
       [ 1.15782128, -0.59918   ,  0.69985365,  0.17887017],
       [-0.61127369,  0.69985365,  1.65231726, -0.82577401]])

##### Dot Product 

In [106]:
# Dot product
a2 = np.arange(12).reshape((3,4))
a3 = np.arange(12,24).reshape((4,3))

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [110]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [111]:
# log and exponents
np.log(a1)

array([[4.35670883, 3.58351894, 2.30258509, 1.09861229],
       [1.38629436, 4.35670883, 4.58496748, 4.44265126],
       [4.02535169, 4.58496748, 4.20469262, 4.07753744]])

In [112]:
np.exp(a1)

array([[7.49841700e+33, 4.31123155e+15, 2.20264658e+04, 2.00855369e+01],
       [5.45981500e+01, 7.49841700e+33, 3.63797095e+42, 8.22301271e+36],
       [2.09165950e+24, 3.63797095e+42, 1.25236317e+29, 4.20121040e+25]])

In [114]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[81., 57., 62.],
       [ 3.,  9., 54.]])

In [115]:
np.floor(np.random.random((2,3))*100)

array([[91., 98., 51.],
       [67., 43., 47.]])

In [116]:
np.ceil(np.random.random((2,3))*100)

array([[ 2., 91., 84.],
       [28.,  9., 71.]])

### Indexing and Slicing

In [117]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [119]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
a1[-1]

9

In [121]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a2[1,2]   # <row,column>

6

In [129]:
a2[1,0]

4

In [130]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [135]:
# I want to take out 5

a3[1,0,1] 

# a3 is combination of two (2*2) 2D array
# So find in which 2D array 5 exists ::: 2nd => index 1
# In the 2D array 5 belongs to which row ::: 1st => index 0
# In the 1st row what is the column in which 5 is there ::: 2nd => index 1

5

In [136]:
a3[0,1,0]

2

In [137]:
a3[1,1,0]

6

##### Slicing

In [138]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
# I want to take out 2,3,4

a1[2:5] #last waala not included :::[start:stop:jitna ka jump+1]

array([2, 3, 4])

In [155]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [156]:
# I want only first row
a2[0,:]  # : => saare cols chahiye

array([0, 1, 2, 3])

In [157]:
a2[:,2]  # : => saara row chahiye

array([ 2,  6, 10])

In [158]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [159]:
# I want 0,3,8,11

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [161]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [162]:
# 1,3,9,11

a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [163]:
# Let's explain
a2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [167]:
# iske baad I am only interested from column 1,9 ahead so 2nd col onwards => index 1 to all with step of 2 as I don't want 2, 10 [1::2]

In [168]:
# I want 4 and 7

a2[1,::3]

array([4, 7])

In [169]:
# I want 1,2,3,5,6,7

a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [171]:
a3 = np.arange(27).reshape(3,3,3)

In [172]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [173]:
a3[1,:,:] #or simply a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [174]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [175]:
# I want 3,4,5

a3[0,1]

array([3, 4, 5])

In [176]:
# I want 10,13,16
a3[1,::,1]

array([10, 13, 16])

In [177]:
# I want 22,23,25,26
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [178]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [181]:
# I want 0,2,18,20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [185]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [183]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
for i in a2:
    print(i) #ek baar mein ek row print hota hai

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [184]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [189]:
for i in a3:
    print(i) # haar baar ek 2D array print hoga

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


##### np.nditer()

In [191]:
for i in np.nditer(a3): #loop through all element
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [192]:
# transpose
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [195]:
a2.T # Simple syntax 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [197]:
# ravel ::: converts any dimension array to 1D
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [198]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [199]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [200]:
# Horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [201]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [202]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [203]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [204]:
# Vertical stacking
np.vstack((a4,a5,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Splitting

In [205]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [207]:
np.hsplit(a4,2) # 2 = kitne equal parts mein aap katna chahte ho

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [209]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [210]:
# Vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [211]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]