### Numpy Tricks

##### np.sort() - Return a sorted copy of an array

In [1]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[16, 19, 30, 54],
       [56, 11, 90, 79],
       [39, 73, 89, 29],
       [34,  3, 33, 57],
       [85, 65, 12, 37],
       [34, 19,  8, 57]])

In [3]:
np.sort(a)

array([ 5,  6,  8, 14, 24, 44, 57, 73, 75, 76, 86, 88, 88, 94, 97])

In [6]:
np.sort(a)[::-1]

array([97, 94, 88, 88, 86, 76, 75, 73, 57, 44, 24, 14,  8,  6,  5])

In [4]:
np.sort(b)

array([[16, 19, 30, 54],
       [11, 56, 79, 90],
       [29, 39, 73, 89],
       [ 3, 33, 34, 57],
       [12, 37, 65, 85],
       [ 8, 19, 34, 57]])

In [5]:
np.sort(b,axis=0)

array([[16,  3,  8, 29],
       [34, 11, 12, 37],
       [34, 19, 30, 54],
       [39, 19, 33, 57],
       [56, 65, 89, 57],
       [85, 73, 90, 79]])

##### np.append()

In [7]:
np.append(a,233)

array([  6,  76,   8,  24,  97,  94,  44,  73,  88,  57,  75,   5,  14,
        86,  88, 233])

In [8]:
b

array([[16, 19, 30, 54],
       [56, 11, 90, 79],
       [39, 73, 89, 29],
       [34,  3, 33, 57],
       [85, 65, 12, 37],
       [34, 19,  8, 57]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[16., 19., 30., 54.,  1.],
       [56., 11., 90., 79.,  1.],
       [39., 73., 89., 29.,  1.],
       [34.,  3., 33., 57.,  1.],
       [85., 65., 12., 37.,  1.],
       [34., 19.,  8., 57.,  1.]])

##### np.concatenate()

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

In [13]:
np.concatenate((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

##### np.unique()

In [16]:
e = np.array([1,1,1,1,1,2,3,4,5,5,5,6,7,7,7])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7])

##### np.expand_dims

In [17]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [19]:
np.expand_dims(a,axis=0)

array([[ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88]])

In [22]:
np.expand_dims(a,axis=1)

array([[ 6],
       [76],
       [ 8],
       [24],
       [97],
       [94],
       [44],
       [73],
       [88],
       [57],
       [75],
       [ 5],
       [14],
       [86],
       [88]])

In [21]:
np.expand_dims(a,axis=1).shape

(15, 1)

##### np.where()

In [23]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [24]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  5,  7,  8,  9, 10, 13, 14], dtype=int64),)

In [26]:
# Replace all values >50 with 0
#np.where(condition,true hoga to kya karna hai, false hoga to kya karna hai)
np.where(a>50,0,a)

array([ 6,  0,  8, 24,  0,  0, 44,  0,  0,  0,  0,  5, 14,  0,  0])

In [29]:
np.where(a%2==0,0,a)

array([ 0,  0,  0,  0, 97,  0,  0, 73,  0, 57, 75,  5,  0,  0,  0])

##### np.argmax -> returns indices of the max element of the array in a particular axis

In [30]:
b

array([[16, 19, 30, 54],
       [56, 11, 90, 79],
       [39, 73, 89, 29],
       [34,  3, 33, 57],
       [85, 65, 12, 37],
       [34, 19,  8, 57]])

In [32]:
np.argmax(b,axis=0)

array([4, 2, 1, 1], dtype=int64)

In [33]:
np.argmax(b,axis=1)

array([3, 2, 2, 3, 0, 3], dtype=int64)

##### np.argmin

In [34]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [35]:
np.argmin(a)

11

In [36]:
np.argmin(b,axis=1)

array([0, 1, 3, 1, 2, 2], dtype=int64)

##### np.cumsum -> cumulative sum over a given axis

In [37]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [38]:
np.cumsum(a)

array([  6,  82,  90, 114, 211, 305, 349, 422, 510, 567, 642, 647, 661,
       747, 835])

In [39]:
b

array([[16, 19, 30, 54],
       [56, 11, 90, 79],
       [39, 73, 89, 29],
       [34,  3, 33, 57],
       [85, 65, 12, 37],
       [34, 19,  8, 57]])

In [42]:
np.cumsum(b) # Axis not given then it will convert it into 1D and then do cumsum

array([  16,   35,   65,  119,  175,  186,  276,  355,  394,  467,  556,
        585,  619,  622,  655,  712,  797,  862,  874,  911,  945,  964,
        972, 1029])

In [41]:
np.cumsum(b,axis=1)

array([[ 16,  35,  65, 119],
       [ 56,  67, 157, 236],
       [ 39, 112, 201, 230],
       [ 34,  37,  70, 127],
       [ 85, 150, 162, 199],
       [ 34,  53,  61, 118]])

In [43]:
np.cumsum(b,axis=0)

array([[ 16,  19,  30,  54],
       [ 72,  30, 120, 133],
       [111, 103, 209, 162],
       [145, 106, 242, 219],
       [230, 171, 254, 256],
       [264, 190, 262, 313]])

##### np.cumprod

In [44]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [45]:
np.cumprod(a)

array([         6,        456,       3648,      87552,    8492544,
        798299136,  765423616,   41349120, -656244736, 1248755712,
       -832602112,  131956736, 1847394304,  -37879808,  961544192])

##### np.percentile 

In [46]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [48]:
np.percentile(a,100) #np.percentile(a,<percentile>)

97.0

In [49]:
np.percentile(a,50)

73.0

In [50]:
np.median(a)

73.0

##### np.histogram -> frequency count

In [51]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [55]:
np.histogram(a,bins=[0,50,100])

(array([6, 9], dtype=int64), array([  0,  50, 100]))

👆 here in the range of 0-50 we have 6 items, 50-100 : 9 items

##### np.corrcoef -> correlation coefficient: returns Pearson product-moment correlation coefficients ::::: It's between -1 and 1 

In [56]:
salary = np.array([20000,34000,25000,350000,60000])
experience = np.array([1,3,3,5,8])
np.corrcoef(salary,experience)

array([[1.        , 0.31380547],
       [0.31380547, 1.        ]])

#### np.isin

In [57]:
# search ek saath multiple items
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [58]:
items=[10,20,30,97,60,73]
np.isin(a,items)

array([False, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False])

In [59]:
a[np.isin(a,items)]

array([97, 73])

##### np.flip

In [60]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [61]:
np.flip(a)

array([88, 86, 14,  5, 75, 57, 88, 73, 44, 94, 97, 24,  8, 76,  6])

In [62]:
b

array([[16, 19, 30, 54],
       [56, 11, 90, 79],
       [39, 73, 89, 29],
       [34,  3, 33, 57],
       [85, 65, 12, 37],
       [34, 19,  8, 57]])

In [64]:
np.flip(b) # row and column both flipping

array([[57,  8, 19, 34],
       [37, 12, 65, 85],
       [57, 33,  3, 34],
       [29, 89, 73, 39],
       [79, 90, 11, 56],
       [54, 30, 19, 16]])

In [66]:
np.flip(b,axis=1)

array([[54, 30, 19, 16],
       [79, 90, 11, 56],
       [29, 89, 73, 39],
       [57, 33,  3, 34],
       [37, 12, 65, 85],
       [57,  8, 19, 34]])

#### np.put

In [67]:
a

array([ 6, 76,  8, 24, 97, 94, 44, 73, 88, 57, 75,  5, 14, 86, 88])

In [71]:
np.put(a,[0,1],[110,420]) # Permanent changes => np.put(a,[index],[value])

In [69]:
a

array([110, 420,   8,  24,  97,  94,  44,  73,  88,  57,  75,   5,  14,
        86,  88])

#### np.delete

In [72]:
a

array([110, 420,   8,  24,  97,  94,  44,  73,  88,  57,  75,   5,  14,
        86,  88])

In [77]:
np.delete(a,[0,2,4]) # np.delete(a,index)

array([420,  24,  94,  44,  73,  88,  57,  75,   5,  14,  86,  88])

### Set Functions

In [82]:
m = np.array([1,2,3,4])
n = np.array([5,4,2,9])
np.union1d(n,m)

array([1, 2, 3, 4, 5, 9])

In [83]:
np.intersect1d(n,m)

array([2, 4])

In [85]:
np.setdiff1d(n,m)

array([5, 9])

In [86]:
np.setdiff1d(m,n)

array([1, 3])

In [87]:
np.setxor1d(n,m)

array([1, 3, 5, 9])

In [89]:
np.in1d(n,1)

array([False, False, False, False])

In [90]:
np.in1d(m,1)

array([ True, False, False, False])

#### np.clip

In [91]:
a

array([110, 420,   8,  24,  97,  94,  44,  73,  88,  57,  75,   5,  14,
        86,  88])

In [92]:
np.clip(a,a_min=24,a_max=75)

array([75, 75, 24, 24, 75, 75, 44, 73, 75, 57, 75, 24, 24, 75, 75])