!['title'](ml_map.png)

#### Sklearn
- Build machine learning models to make predictions or learn patterns within the data and evaluate those predictions 
- It has many in-built ML models

#### Workflow:
1. Get data ready
2. Pick a model (to suit the problem)
3. Fit the model to the data and make a prediction
4. Evaluate the model
5. Improve through experimentations
6. Save and reload your trained model

In [154]:
import sklearn

In [155]:
sklearn.show_versions()


System:
    python: 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:28:07) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\saurabh\Downloads\Practice\Python\conda_env\python.exe
   machine: Windows-11-10.0.22621-SP0

Python dependencies:
      sklearn: 1.3.0
          pip: 23.3.1
   setuptools: 68.2.2
        numpy: 1.26.4
        scipy: 1.12.0
       Cython: None
       pandas: 2.2.1
   matplotlib: 3.8.0
       joblib: 1.2.0
threadpoolctl: 2.2.0

Built with OpenMP: True

threadpoolctl info:
       filepath: C:\Users\saurabh\Downloads\Practice\Python\conda_env\Library\bin\mkl_rt.2.dll
         prefix: mkl_rt
       user_api: blas
   internal_api: mkl
        version: 2023.1-Product
    num_threads: 10
threading_layer: intel

       filepath: C:\Users\saurabh\Downloads\Practice\Python\conda_env\vcomp140.dll
         prefix: vcomp
       user_api: openmp
   internal_api: openmp
        version: None
    num_threads: 12

       filepath: C:\Users\saurabh\Downloads\Practice\

In [156]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
heart_disease = pd.read_csv('heart-disease.csv')

In [157]:
heart_disease.sample(5)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
161   55    0   1       132   342    0        1      166      0      1.2   
251   43    1   0       132   247    1        0      143      1      0.1   
133   41    1   1       110   235    0        1      153      0      0.0   
138   57    1   0       110   201    0        1      126      1      1.5   
87    46    1   1       101   197    1        1      156      0      0.0   

     slope  ca  thal  target  
161      2   0     2       1  
251      1   4     3       0  
133      2   0     2       1  
138      1   0     1       1  
87       2   0     3       1

In [158]:
heart_disease.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [159]:
# Create X (feature matrix)
X = heart_disease.drop('target',axis=1)
X

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [160]:
# Create y (labels)
y = heart_disease['target']
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [161]:
# Choose the right model and hyper-parameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)

# Keep the default parameters here
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

##### Fit the model to the training data

In [162]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2) # test_size=0.2 => 80% data is used for training, 20% for testing

In [163]:
clf.fit(X_train,y_train);

In [164]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
301   57    1   0       130   131    0        1      115      1      1.2   
75    55    0   1       135   250    0        0      161      0      1.4   
124   39    0   2        94   199    0        1      179      0      0.0   
22    42    1   0       140   226    0        1      178      0      0.0   
230   47    1   2       108   243    0        1      152      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
13    64    1   3       110   211    0        0      144      1      1.8   
6     56    0   1       140   294    0        0      153      0      1.3   
66    51    1   2       100   222    0        1      143      1      1.2   
133   41    1   1       110   235    0        1      153      0      0.0   
157   35    1   1       122   192    0        1      174      0      0.0   

     slope  ca  thal  
301      1   1     3  
75       1   0     2  
124      2   0     2  
22       2   0     2  
230      2   0     2  
..     ...  ..   ...  
13       1   0     2  
6        1   0     2  
66       1   0     2  
133      2   0     2  
157      2   0     2  

[242 rows x 13 columns]

##### Make predictions

In [165]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
130   54    0   2       160   201    0        1      163      0      0.0   
188   50    1   2       140   233    0        1      163      0      0.6   
223   56    0   0       200   288    1        0      133      1      4.0   
34    51    1   3       125   213    0        0      125      1      1.4   
203   68    1   2       180   274    1        0      150      1      1.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
167   62    0   0       140   268    0        0      160      0      3.6   
264   54    1   0       110   206    0        0      108      1      0.0   
147   60    0   3       150   240    0        1      171      0      0.9   
60    71    0   2       110   265    1        0      130      0      0.0   
257   50    1   0       144   200    0        0      126      1      0.9   

     slope  ca  thal  
130      2   1     2  
188      1   1     3  
223      0   2     3  
34       2   1     2  
203      1   0     3  
..     ...  ..   ...  
167      0   2     2  
264      1   1     2  
147      2   0     2  
60       2   1     2  
257      1   0     3  

[61 rows x 13 columns]

In [166]:
y_preds = clf.predict(X_test) # prediction can be done on data which looks similar  shpae to train so X_test

In [167]:
y_preds

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [168]:
y_test

130    1
188    0
223    0
34     1
203    0
      ..
167    0
264    0
147    1
60     1
257    0
Name: target, Length: 61, dtype: int64

##### Evaluate the model

In [169]:
clf.score(X_train, y_train) # Result on training data

1.0

In [170]:
clf.score(X_test,y_test) # Result on test data

0.9016393442622951

In [171]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.89      0.89      0.89        27
           1       0.91      0.91      0.91        34

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61



In [172]:
confusion_matrix(y_test,y_preds)

array([[24,  3],
       [ 3, 31]], dtype=int64)

In [173]:
accuracy_score(y_test, y_preds)

0.9016393442622951

##### Improve a model

In [174]:
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f'Trying model with {i} estimators...')
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f'Model accuracy on test data set:{clf.score(X_test,y_test)*100:2f}%')
    print("")

Trying model with 10 estimators...
Model accuracy on test data set:88.524590%

Trying model with 20 estimators...
Model accuracy on test data set:86.885246%

Trying model with 30 estimators...
Model accuracy on test data set:83.606557%

Trying model with 40 estimators...
Model accuracy on test data set:90.163934%

Trying model with 50 estimators...
Model accuracy on test data set:90.163934%

Trying model with 60 estimators...
Model accuracy on test data set:90.163934%

Trying model with 70 estimators...
Model accuracy on test data set:88.524590%

Trying model with 80 estimators...
Model accuracy on test data set:88.524590%

Trying model with 90 estimators...
Model accuracy on test data set:90.163934%



##### Save a model and load it

In [175]:
import pickle
pickle.dump(clf,open('random_forest_model1.pkl','wb'))

In [176]:
loaded_model = pickle.load(open('random_forest_model1.pkl','rb'))
loaded_model.score(X_test,y_test)

0.9016393442622951

#### Getting our data ready 
Three main things we have to do:
1. Split the data into features and labels (Usually `X` and `y`)
2. Filling (also called <b>imputing</b>) or disregarding missing values
3. Converting non-numerical values to numerical values (also called <b>Feature Encoding</b>)

In [177]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [178]:
X = heart_disease.drop('target',axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [179]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

##### Splitting the data into training and test sets

In [180]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [181]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [182]:
X.shape

(303, 13)

In [183]:
len(heart_disease)

303

In [184]:
X.shape[0]*0.8

242.4

##### Clean Data -> Transform Data -> Reduce Data

### 1.1 Make sure it's all numerical

In [185]:
car_sales = pd.read_csv('car-sales.csv')

In [186]:
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [187]:
len(car_sales)

1000

In [188]:
# Split the data into X/y
X = car_sales.drop('Price',axis=1)
y = car_sales['Price']

In [189]:
# Splitting into training and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [190]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train,y_train)

model.score(X_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [191]:
# ML models can't deal with strings so we need to convert them into integers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder='passthrough')

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [192]:
X.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [193]:
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

![OneHotEncoding.png](OHE.png)

In [194]:
dummies = pd.get_dummies(car_sales[['Make','Colour','Doors']])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4     False        True        False        False         False   
1        5      True       False        False        False         False   
2        4     False        True        False        False         False   
3        4     False       False        False         True         False   
4        3     False       False         True        False         False   
..     ...       ...         ...          ...          ...           ...   
995      4     False       False        False         True          True   
996      3     False       False         True        False         False   
997      4     False       False         True        False         False   
998      4     False        True        False        False         False   
999      4     False       False        False         True         False   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          False         False       False          True  
1           True         False       False         False  
2          False         False       False          True  
3          False         False       False          True  
4           True         False       False         False  
..           ...           ...         ...           ...  
995        False         False       False         False  
996        False         False       False          True  
997         True         False       False         False  
998        False         False       False          True  
999         True         False       False         False  

[1000 rows x 10 columns]

In [195]:
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,y,test_size=0.2)
model.fit(X_train,y_train)

RandomForestRegressor()

In [196]:
model.score(X_test, y_test)

0.3235867221569877

### 1.2 What if there were missing values?
- Fill them with some value (also known as imputation)
- Remove the samples with missing data altogether

In [205]:
car_sales_missing = pd.read_csv('car_sales_missing_data.csv')

In [206]:
car_sales_missing.sample(5)

Make Colour  Odometer (KM)  Doors    Price
787  Toyota  White       245977.0    4.0  11036.0
698  Nissan  White        66199.0    4.0  27557.0
836  Nissan   Blue        69954.0    4.0  20938.0
695  Toyota  White       146824.0    4.0  16285.0
635   Honda    Red       101835.0    4.0  16110.0

In [207]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [208]:
X = car_sales_missing.drop('Price',axis=1)
y = car_sales_missing['Price']

In [209]:
# Let's try to convert our data into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder='passthrough')

transformed_X = transformer.fit_transform(X)
transformed_X

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

In [203]:
X

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW   Blue       192714.0    5.0
2     Honda  White        84714.0    4.0
3    Toyota  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996     NaN  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[1000 rows x 4 columns]

In [204]:
y.isna().sum()

50

##### Yes, you can perform hot encoding on data with NaN values. However, there are a few things to keep in mind:
- NaN values will be encoded as a separate category. This means that your one-hot encoded dataframe will have an extra column for NaN values.
- You may need to impute the NaN values before performing hot encoding. This is because some machine learning algorithms cannot handle NaN values.
- You should be careful not to overfit your model to the NaN values. This can happen if you have a lot of NaN values in your data.ta.

##### Option 1: Fill missing data with Pandas

In [217]:
car_sales_missing['Make'] = car_sales_missing['Make'].fillna('missing')
car_sales_missing['Colour'] = car_sales_missing['Colour'].fillna('missing')
car_sales_missing['Odometer (KM)'] = car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean())
car_sales_missing['Doors'] = car_sales_missing['Doors'].fillna(4)

In [218]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [219]:
car_sales_missing.dropna(inplace=True)

In [220]:
len(car_sales_missing)

950

In [221]:
# Create X and y
X = car_sales_missing.drop('Price',axis=1)
y = car_sales_missing['Price']

In [222]:
# Let's try to convert our data into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

##### Option 2: Fill missing data with Scikit-Learn

In [224]:
car_sales_missing = pd.read_csv('car_sales_missing_data.csv')
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [225]:
car_sales_missing.dropna(subset=['Price'],inplace=True)

In [226]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [227]:
# Split into X and y
X = car_sales_missing.drop('Price',axis=1)
y = car_sales_missing['Price']

In [233]:
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [234]:
# Fill missing values with sklean
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' and numerical values with mean
cat_imputer = SimpleImputer(strategy='constant', fill_value='missing')
door_imputer = SimpleImputer(strategy='constant',fill_value=4)
num_imputer = SimpleImputer(strategy='mean')

# Define columns
cat_features = ['Make','Colour']
door_feature = ['Doors'] 
num_features = ['Odometer (KM)']

# Create an imputer (something that fills missing data)
imputer = ColumnTransformer(
    [
        ('cat_imputer',cat_imputer,cat_features),
        ('door_imputer',door_imputer,door_feature),
        ('num_imputer',num_imputer,num_features),
    ]
)

# Transform the data
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [235]:
car_sales_filled = pd.DataFrame(filled_X, columns=['Make','Colour','Doors','Odometer (KM)'])
car_sales_filled.sample(5)

Make Colour Doors Odometer (KM)
799  Toyota   Blue   4.0      125939.0
426  Nissan  Green   4.0       90446.0
237  Nissan  White   4.0      196374.0
429   Honda   Blue   4.0       73286.0
465  Nissan  White   4.0       51004.0

In [236]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [237]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make','Colour','Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',one_hot,categorical_features)],remainder='passthrough')

transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [238]:
# Now we have got our data as numbers and filled (no missing values)
# Let's fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X,y,test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test,y_test)

0.21990196728583944

In [239]:
len(car_sales_filled), len(car_sales)

(950, 1000)

### 2. Choosing the right estimator/algorithm for our problem
Scikit-Learn uses estimator as another term for machine learning model or algorithm
- <b>Classification</b> : Predicting whether a sample is one thing or another
- <b>Regression</b> : Predicting a number

#### 2.1 Picking a machine learning model for a regression problem

In [245]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [249]:
California_df = pd.DataFrame(housing['data'],columns=housing.feature_names)
California_df.sample(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
20111  3.4838      30.0  7.206061   1.545455       446.0  2.703030     37.80   
7826   3.5972      26.0  5.000000   1.097902      1150.0  2.680653     33.90   
3820   2.6957      23.0  3.667954   1.111969      2249.0  2.894466     34.20   
9594   3.2852      17.0  5.535326   1.060688      2950.0  2.672101     37.33   
5320   4.8304      38.0  5.216649   1.201708      1698.0  1.812166     34.05   

       Longitude  
20111    -120.20  
7826     -118.14  
3820     -118.48  
9594     -120.46  
5320     -118.42

In [251]:
California_df['target'] = pd.Series(housing['target'])
California_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  target  
0    -122.23   4.526  
1    -122.22   3.585  
2    -122.24   3.521  
3    -122.25   3.413  
4    -122.25   3.422

In [253]:
California_df.shape

(20640, 9)

In [255]:
# Let's try the Ridge Regression model
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(42)

# Create the data
X = California_df.drop('target',axis=1)
y = California_df['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate Ridge model
model = Ridge()
model.fit(X_train,y_train)

model.score(X_test,y_test)

0.5758549611440126

##### How do we improve this score?
##### What if Ridge wasn't working?
Map: https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

- <b>Ensemble methods</b> combine the predictions of several base estimators built with a given learning algorithm in order to improve generalizability / robustness over a single estimator.
- Two very famous examples of ensemble methods are:
   1. Gradient-boosted trees
   2. Random forests.

In [273]:
# Let's try the RandomForest Regressor
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create the data
X = California_df.drop('target',axis=1)
y = California_df['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate RandomForestRegressor model
clf = RandomForestRegressor()
clf.fit(X_train,y_train)

clf.score(X_test,y_test)

0.8065734772187598

In [261]:
model.score(X_test,y_test)

0.5758549611440126

#### 2.2 Choosing an estimator for a classification problem
Let's go to the map : https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [263]:
heart_disease = pd.read_csv('heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [264]:
len(heart_disease)

303

In [270]:
# Let's try linear SVC
from sklearn.svm import LinearSVC

# Setup random seed
np.random.seed(42)

# Create the data
X = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate RandomForestClassifier model
clf = LinearSVC()
clf.fit(X_train,y_train)

clf.score(X_test,y_test)

C:\Users\saurabh\Downloads\Practice\Python\conda_env\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\saurabh\Downloads\Practice\Python\conda_env\Lib\site-packages\sklearn\svm\_base.py:1242: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

In [271]:
heart_disease['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

In [272]:
# Let's try the RandomForest Classifier 
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Create the data
X = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate RandomForestClassifier model
clf = RandomForestClassifier()
clf.fit(X_train,y_train)

clf.score(X_test,y_test)

0.8524590163934426

#### Tidbit:
    1. If you have structured data, use ensemble methods
    2. If you have unstructured data, use deep learning or transfer learning 

### 3. Fit the model/algorithm on our data and use it to make predictions
#### 3.1 Fitting the model to the data
Different names for:
- X = features, features variables, data
- y = labels, targets, target variables

In [275]:
# Let's try the RandomForest Classifier 
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Create the data
X = heart_disease.drop('target',axis=1)
y = heart_disease['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate RandomForestClassifier model
clf = RandomForestClassifier()
clf.fit(X_train,y_train)

clf.score(X_test,y_test)

0.8524590163934426

In [276]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [278]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

In [277]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

#### 3.2 Make predictions using a machine learning model
2 Ways to make predictions:
1. `predict()`
2. `predict_proba()`

In [279]:
# Using a trained model to make predictions
clf.predict(np.array([1,4,6,8,5])) # this doesn't work

C:\Users\saurabh\Downloads\Practice\Python\conda_env\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[1. 4. 6. 8. 5.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [280]:
X_test.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

In [281]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [284]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [285]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds==y_test)

0.8524590163934426

In [286]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

In [289]:
clf.score(X_test,y_test)

0.8524590163934426

Make predictions with `predict_proba()`
- predict_proba() returns probabilities of a classification 

In [291]:
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [293]:
# Let's predict() on the same data
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

In [294]:
heart_disease['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

`predict()` can also be used for regression model

In [298]:
# Let's try the RandomForest Regressor
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create the data
X = California_df.drop('target',axis=1)
y = California_df['target']

# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

# Initiate RandomForestRegressor model
model = RandomForestRegressor().fit(X_train,y_train)

# Make Predictions
y_preds = model.predict(X_test)

In [299]:
y_preds[:10]

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [300]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [301]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds)

0.32659871732073664